# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

defmodule Problem2 do
  def solve do
    # IO.puts  Enum.reduce((Enum.filter((Enum.to_list 1..999), fn(x) -> (rem(x, 3) == 0 || rem(x, 5) == 0) end)), 0, &(&1 + &2) )
  end
end

Problem2.solve
